const demo = {
  source: 'truyen.tangthuvien.vn',
  book_id: '33300',
  img_url:
    'https://www.nae.vn/ttv/ttv/public/images/story/725a06cc62762c8dc79e9a86146a7c268736b8ed26d8e5289c9f392b7589f5bb.jpg',
  book_name: 'Luyện Ngục Nghệ Thuật Gia  - 炼狱艺术家 ',
  book_author: '\nYên Hỏa Thành Thành\n',
  book_intro:
    ' Phiên bản chính thức:\n\r\nTrong ban đêm vùng cực đen kịt tĩnh mịch, chỉ còn lại có cuối cùng một mồi lửa có thể bảo hộ mọi người, thế là ta đưa nó giơ lên dùng sức thổi, ta thổi ta thổi, một lòng muốn cho mồi lửa này ngày càng sáng hơn, sáng đến đủ để chiếu rọi hết thảy.\n\r\nThế nhưng thật có lỗi, ta lại thổi tắt nó rồi.\n\r\nPhiên bản không chính thức:\n\r\nRõ ràng chuẩn bị cứu vớt thế giới lại bị sư phụ một chưởng đánh chết ta tỉnh lại lập tức phát hiện hai cái bí mật: Tử Vong Thế Giới có quái vật, ta phải lập tức bước đi.',
  chapter_name: [
    'Chương 1 : Phần đệm + Kẻ theo dõi (Quyển 1: Mở đầu)',
    'Chương 2 : Ống heo tiết kiệm',
    'Chương 3 : Lại đến',
    'Chương 4 : Quái vật',
    'Chương 5 : Ép hỏi',
    'Chương 6 : 1 người không có phần diễn',
    'Chương 7 : Chạy trốn',
    'Chương 8 : Gặp chúng',
    'Chương 9 : Sứ giả nhìn trộm',
    'Chương 10 : Thiên Trụy',
    'Chương 11 : Tiếp địch!',
    'Chương 12 : Một tuồng kịch (Xong Quyển 1)',
    'Chương 13 : Đêm cùng ban ngày (Quyển 2: Hắc Ám Hí Kịch)',
    'Chương 14 : Ám Vụ trấn',
    'Chương 15 : Tử vong lan tràn',
    'Chương 16 : Gác đêm',
    'Chương 17 : Bắt đầu!',
    'Chương 18 : Tiên nhân phủ trước mặt',
    'Chương 19 : Kết tóc thụ trường sinh',
    'Chương 20 : Sách Người Gác Đêm',
    'Chương 21 : Binh khí',
    'Chương 22 : Cửu U',
    'Chương 23 : Vì phần diễn',
    'Chương 24 : Bàn về chuyện xưa cũ',
    'Chương 25 : Đáy vực',
    'Chương 26 : Đêm dài',
    'Chương 27 : Mật thất cùng mật thất',
    'Chương 28 : Pho tượng cùng hư không thần thông',
    'Chương 29 : Phục sinh',
    'Chương 30 : Bắt đầu lại từ đầu!',
    'Chương 31 : Người thổi lửa',
    'Chương 32 : Hắn kẹp lại',
  ],
  chapter_link: [
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-1',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-2',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-3',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-4',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-5',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-6',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-7',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-8',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-9',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-10',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-11',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-12',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-13',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-14',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-15',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-16',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-17',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-18',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-19',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-20',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-21',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-22',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-23',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-24',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-25',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-26',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-27',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-28',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-29',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-30',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-31',
    'https://truyen.tangthuvien.vn/doc-truyen/luyen-nguc-nghe-thuat-gia/chuong-32',
  ],
  season_name: ['Quyển 1  - Mở đầu ', 'Quyển 2  - Hắc ám hí kịch '],
  season_index: [0, 12, 32],
};

const BooksData = [
  demo,
  {
    book_name: 'Dracula',
    book_author: 'Bram Stoker',
    img_url: 'https://m.media-amazon.com/images/I/5126hLd7jsL.jpg',
    book_intro:
      'In appearance, Count Dracula is described as being a "tall old man, clean shaven, save for a long white mustache and clad in black from head to foot, without a single speck of color about him anywhere." Contrary to popular understanding, Stoker has his Dracula sporting a large, bushy Victorian mustache and having a',
  },
  {
    book_name: 'Les Misérables',
    book_author: 'Victor Hugo',
    img_url: 'https://m.media-amazon.com/images/I/51fyLYwnWwL.jpg',
    book_intro: '',
  },
  {
    book_name: 'A Tramp Abroad',
    book_author: 'Mark Twain',
    img_url: 'https://m.media-amazon.com/images/I/61pnmTS-GGL.jpg',
    book_intro: '',
  },
  {
    book_name: 'A Japanese Boy',
    book_author: 'Shigemi Shiukichi',
    img_url:
      'https://images-na.ssl-images-amazon.com/images/I/51oWe+bDTqL._SX331_BO1,204,203,200_.jpg',
    book_intro: '',
  },
  {
    book_name: 'The Tale of Peter Rabbit',
    book_author: 'Beatrix Potter',
    img_url: 'https://images-na.ssl-images-amazon.com/images/I/A1KzHvAir+L.jpg',
    book_intro: '',
  },
];

export default BooksData;
